repo: https://github.com/pre-commit/pre-commit-hooks
rev: v1.0.0   
hooks:
-   id: trailing-whitespace
-   id: check-json
-   id: check-merge-conflict
-   id: check-toml
-   id: check-yaml
-   id: check-symlinks
-   id: detect-aws-credentials
-   id: detect-private-key